baseurl = "http://raintank.io/"
languageCode = "en-us"
title = "raintank"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
  section = "section"


[[menu.main]]
    name = "Grafana.net"
    weight = -110
    identifier = "grafana-net"
    url = "http://grafana.net"

[[menu.main]]
    name = "about"
    weight = -110
    identifier = "about"
    url = "/about/"

[[menu.main]]
    name = "the raintank vision"
    weight = -110
    identifier = "vision"
    url = "/about/"
    parent = "about"

[[menu.main]]
    name = "about the team"
    weight = -100    
    identifier = "team"
    url = "/about/team"
    parent = "about"

[[menu.main]]
    name = "work with us"
    weight = -90    
    identifier = "join"
    url = "/about/join"
    parent = "about"


[[menu.main]]
    name = "grafana"
    weight = -110
    identifier = "grafana"
    url = "/grafana/"



[[menu.main]]
    name = "software"
    weight = -90
    identifier = "software"
    url = "/software/"

[[menu.main]]
    name = "worldPing"
    weight = -110
    identifier = "worldping"
    url = "http://worldping.com"
    parent = "software"

[[menu.main]]
    name = "Grafana"
    weight = -100    
    identifier = "grafana"
    url = "http://grafana.org"
    parent = "software"


[[menu.main]]
    name = "blog"
    weight = -50
    identifier = "blog"
    url = "http://blog.raintank.io"

